[package]
name = "rustic"
version = "0.1.0"
edition = "2024"

[dependencies]

anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
fs_extra = "1.3"
gray_matter = "0.2"
pulldown-cmark = "0.9"
serde = { version = "1.0", features = ["derive"] }
tera = "1"
walkdir = "2"